### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mega94** [dev-efabrica/translation-automatization#31]
Make a use case on pure php

**Comment by lulco** [comment]
Hi @mega94 can you elaborate? How would we do that? We need to know how to identify tokens, which translator to use etc. Can you explain what do you need?

**Comment by mega94** [comment]
> Привет @ mega94, можешь уточнить? Как бы мы это сделали? Нам нужно знать, как идентифицировать токены, какой переводчик использовать и т. Д. Вы можете объяснить, что вам нужно?

An example of using the Bing translator, I myself am trying to connect like this:  
```
<?php

use Efabrica\TranslationsAutomatization\Translator\BingTranslator;

$tr = new BingTranslator("en", "ru", 1000);
echo $tr->translate("hello world");
```

But I am getting error.

**Comment by lulco** [comment]
Is your error:
```
TypeError: Argument 1 passed to Efabrica\TranslationsAutomatization\Translator\BingTranslator::translate() must be of the type array, string given
```
?

That's because translate method needs array as parameter, so change your code to:

```
<?php 

use Efabrica\TranslationsAutomatization\Translator\BingTranslator;

$tr = new BingTranslator("en", "ru", 1000);
print_R($tr->translate(["hello world"]));
```

and it will work...

**Comment by mega94** [comment]
> Is your error:
> 
> ```
> TypeError: Argument 1 passed to Efabrica\TranslationsAutomatization\Translator\BingTranslator::translate() must be of the type array, string given
> ```
> 
> ?
> 
> That's because translate method needs array as parameter, so change your code to:
> 
> ```
> <?php 
> 
> use Efabrica\TranslationsAutomatization\Translator\BingTranslator;
> 
> $tr = new BingTranslator("en", "ru", 1000);
> print_R($tr->translate(["hello world"]));
> ```
> 
> and it will work...

Please tell me what restrictions have you stumbled upon?

**Comment by mega94** [comment]
I get that kind of error: ```Array ( [StatusCode] => 429 [ShowCaptcha] => 1 )``` `Notice: Undefined offset: 0 in /home/n/name/domen/public_html/opencart/vendor/efabrica/translation-automatization/src/Translator/BingTranslator.php on line 41Notice:`

**Comment by lulco** [comment]
- rate limit (too many calls will block you)
- for more texts we use `|` as separator so you cannot use it as part of texts
- bing translates everything, so if we have text with tokens for example `My name is %name%` Bing sometimes translates it to `Moje meno je % meno%`- it translated token between %% and adds space after first %

**Comment by lulco** [comment]
> I get that kind of error: `Array ( [StatusCode] => 429 [ShowCaptcha] => 1 )` `Notice: Undefined offset: 0 in /home/n/name/domen/public_html/opencart/vendor/efabrica/translation-automatization/src/Translator/BingTranslator.php on line 41Notice:`

Yeah you probably hit the rate limit. Status code 429 is means too many requests.

Check this:
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/request-limits

**Comment by mega94** [comment]
> Check this:



> > I get that kind of error: `Array ( [StatusCode] => 429 [ShowCaptcha] => 1 )` `Notice: Undefined offset: 0 in /home/n/name/domen/public_html/opencart/vendor/efabrica/translation-automatization/src/Translator/BingTranslator.php on line 41Notice:`
> 
> Yeah you probably hit the rate limit. Status code 429 is means too many requests.
> 
> Check this:
> https://docs.microsoft.com/en-us/azure/cognitive-services/translator/request-limits

I guess my ip will be thrown at the eternal, Is it possible to bypass 429 because it is a long-standing error

**Comment by lulco** [comment]
Maybe it exists some paid version with higher request limits. But as we didn't need it for now, we didn't implement it. Also you can implement Google translator with some api tokens instead.

**Comment by lulco** [comment]
Hello @mega94 recently we implemented google translator (some free version), you can try it https://github.com/dev-efabrica/translation-automatization/blob/master/src/Translator/GoogleTranslator.php

**Comment by mega94** [comment]
> Hello @mega94 recently we implemented google translator (some free version), you can try it https://github.com/dev-efabrica/translation-automatization/blob/master/src/Translator/GoogleTranslator.php

Hi, is it possible to send an array of words and get an array of translations like in the picture?

https://sun9-51.userapi.com/impg/uYgs8A-vtvd21iIZeR54_aoHs8lvaXz6_psQkA/RgpnyEB0mwU.jpg?size=815x555&quality=96&sign=077a15208314614cede53f5b6923bf71&type=album

https://sun9-65.userapi.com/impg/-5I-HuDwuIASBqao9rc8W2bS30BBu6OzVXXDyQ/K6xafz3ZMMQ.jpg?size=725x582&quality=96&sign=a2fbfe8478de0df8df7c4a8703223978&type=album

This approach will shorten the request and speed up bulk transfers.

**Comment by lulco** [comment]
What kind of translator is on screenshots? Our translator works as you described: you send an array of words to it and it returns this array of words as keys and translations as values of array.

**Comment by mega94** [comment]
> What kind of translator is on screenshots? Our translator works as you described: you send an array of words to it and it returns this array of words as keys and translations as values of array.

The approach to glue several sentences together, and then break up, does this approach provide a high-quality translation?
And next, sometimes I get errors: `Warning: array_combine(): Both parameters should have an equal number of elements in /home/n/server/asdasd/asdasd/asdasd/vendor/efabrica/translation-automatization/src/Translator/GoogleTranslator.php on line 46`

**Comment by lulco** [comment]
Yes, it is not ideal. Like you wrote, sometimes we get this error. Thats why I've asked you what kind of translator is used in your screenshots. If it is the same like we are using, we can change request to multiple `q` parameter. Feel free to send pull request

**Comment by mega94** [comment]
> Yes, it is not ideal. Like you wrote, sometimes we get this error. Thats why I've asked you what kind of translator is used in your screenshots. If it is the same like we are using, we can change request to multiple `q` parameter. Feel free to send pull request

this is the translation that can be obtained from the browser, right-click and call the function 'translate page' there is a complex algorithm for obtaining a translation, I do not know how to get it
